/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import jade.core.Agent;
import utilidad.MensajeConsola;

/**
 *
 * @author Hugo
 */
public class ConsolaJFrame extends javax.swing.JFrame {
    private Agent agenteAsociado; //Nombre del agente consola asociado.
    private OkCancelJDialog dialogoFinalizacion;
    
    /**
     * Creates new form ConsolaJFrame
     */
    public ConsolaJFrame(Agent asociado) {
        this.agenteAsociado = asociado;
        initComponents();
        setTitle(asociado.getName());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        texto.setViewportView(areaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dialogoFinalizacion = new OkCancelJDialog(this, true, agenteAsociado);
        dialogoFinalizacion.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void presentarSalida(MensajeConsola mc)
    {
        if(!isVisible())
            setVisible(true);
        
        areaTexto.append(mc.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JScrollPane texto;
    // End of variables declaration//GEN-END:variables
}
